config/routes.rb
Rails.application.routes.draw do
  # Have a path just for checking uptime, a no frills things to just check we're alive
  get :uptime_check, path: 'uptime-check', to: proc { [200, {}, ["Hello Robot - We're still up"]] }

  constraints subdomain: 'api' do
    namespace :api do
      namespace :v1 do
        resources :reports, only: [:create], defaults: { formats: :json }
      end
    end
    get '/', to: redirect("https://#{ENV['URL']}/api")
  end

  constraints subdomain: 'webhooks' do
    namespace :webhooks do
      resources :github, only: [:create], defaults: { formats: :json }
    end
    get '/', to: redirect("https://#{ENV['URL']}")
  end

  constraints subdomain: ['', 'www'] do
    devise_for :users,
               path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 sign_up: 'join-us'
               }, controllers: {
                 sessions: 'users/sessions',
                 omniauth_callbacks: 'users/omniauth_callbacks'
               }

    namespace :setup do
      resource :github, only: [:show]
    end

    resource :billing, only: [:show]
    resource :settings, only: [:show]

    resources :projects do
      member do
        get :delete
        get :setup
      end
      resources :report_collections, only: [:show] do
        resources :reports, only: [:show]
      end
    end

    get 'api', to: 'landing#api'
    get 'contact-us', to: 'landing#contact_us'
    get 'roadmap', to: 'landing#roadmap'

    get 'privacy-policy', to: 'legals#privacy_policy'
    get 'terms-of-service', to: 'legals#terms_of_service'
    get 'cookie-policy', to: 'legals#cookie_policy'
    get 'subprocessors', to: 'legals#subprocessors'
    get 'github-integration-deprecation-notice', to: 'legals#github_integration_deprecation_notice'

    get '', to: 'landing#index'
  end

  mount MountainView::Engine => '/styleguide'

  root to: redirect("https://#{ENV['URL']}")
end

app/views/shared/header/_brand.html.erb
<%= link_to root_path, class: 'navbar-brand' do %>
  <%= render_logo %>
  <span class="pigci-brand d-inline-block align-middle">PigCI</span>
<% end %>

app/views/shared/header/_navbar_guest.html.erb
<nav class="navbar navbar-light px-0">
  <%= render 'shared/header/brand' %>

  <div class="navbar-nav ml-auto">
    <div class="pigci-nav-button-container">
      <%= link_to 'Get Started', Rails.application.credentials.dig(Rails.env.to_sym, :github, :install_url), class: 'btn btn-primary btn-sm' %>
      <%= link_to 'Log In', new_user_session_path, class: 'btn btn-outline-primary btn-sm' %>
    </div>
  </div>
</nav>

app/views/shared/header/_navbar_user.html.erb
<nav class="navbar navbar-expand-lg navbar-light px-0">
  <%= render 'shared/header/brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-2 d-block d-lg-none mt-2 text-center">
      <li class="nav-item">
        <%= link_to Project.name.pluralize, projects_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Settings', settings_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Billing', billing_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, class: 'nav-link', method: :delete %>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto d-none d-lg-inline-block list-inline">
      <li class="nav-item list-inline-item">
        <%= link_to Project.name.pluralize, projects_path, class: 'btn btn-sm btn-outline-primary mr-2' %>
      </li>

      <li class="nav-item list-inline-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag current_user.avatar_url, width: 20, height: 20, class: 'rounded mr-1', alt: current_user %>
          <%= current_user.to_s %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Settings', settings_path, class: 'dropdown-item' %>
          <%= link_to 'Billing', billing_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Logout', destroy_user_session_path, class: 'dropdown-item', method: :delete %>
        </div>
      </li>
    </ul>
  </div>
</nav>