config/routes.rb
Rails.application.routes.draw do
  # Have a path just for checking uptime, a no frills things to just check we're alive
  get :uptime_check, path: 'uptime-check', to: proc { [200, {}, ["Hello Robot - We're still up"]] }

  constraints subdomain: 'api' do
    namespace :api do
      namespace :v1 do
        resources :reports, only: [:create], defaults: { formats: :json }
      end
    end
    get '/', to: redirect("https://#{ENV['URL']}/api")
  end

  constraints subdomain: 'webhooks' do
    namespace :webhooks do
      resources :github, only: [:create], defaults: { formats: :json }
    end
    get '/', to: redirect("https://#{ENV['URL']}")
  end

  constraints subdomain: ['', 'www'] do
    devise_for :users,
               path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 sign_up: 'join-us'
               }, controllers: {
                 sessions: 'users/sessions',
                 omniauth_callbacks: 'users/omniauth_callbacks'
               }

    namespace :setup do
      resource :github, only: [:show]
    end

    resource :billing, only: [:show]
    resource :settings, only: [:show]

    resources :projects do
      member do
        get :delete
        get :setup
      end
      resources :report_collections, only: [:show] do
        resources :reports, only: [:show]
      end
    end

    get 'api', to: 'landing#api'
    get 'contact-us', to: 'landing#contact_us'
    get 'roadmap', to: 'landing#roadmap'

    get 'privacy-policy', to: 'legals#privacy_policy'
    get 'terms-of-service', to: 'legals#terms_of_service'
    get 'cookie-policy', to: 'legals#cookie_policy'
    get 'subprocessors', to: 'legals#subprocessors'
    get 'github-integration-deprecation-notice', to: 'legals#github_integration_deprecation_notice'

    get '', to: 'landing#index'
  end

  mount MountainView::Engine => '/styleguide'

  root to: redirect("https://#{ENV['URL']}")
end

app/views/shared/_footer.html.erb
<div class="pigci-footer">
  <div class="container">
  
    <div class="row">
      <div class="col-md-3">
        <div class="h5">Product</div>
        
        <ul class="list-unstyled">
          <li>
            <%= link_to 'Pricing', root_path(anchor: 'pricing') %>
          </li>
          <li>
            <%= link_to 'Add via GitHub', Rails.application.credentials.dig(Rails.env.to_sym, :github, :install_url), target: '_blank', rel: 'noopener' %>
          </li>
          <li>
            <%= link_to 'Ruby on Rails Gem', 'https://github.com/PigCI/pig-ci-rails', target: '_blank', rel: 'noopener' %>
          </li>
        </ul>
      </div>

      <div class="col-md-3">
        <div class="h5">Product</div>
        
        <ul class="list-unstyled">
          <li>
            <%= link_to 'API', api_path %>
          </li>
          <li>
            <%= link_to 'Contact Us', contact_us_path %>
          </li>
          <li>
            <%= link_to 'Roadmap', roadmap_path %>
          </li>
        </ul>
      </div>

      <div class="col-md-3">
        <div class="h5">Social</div>

        <ul class="list-unstyled">
          <li>
            <%= link_to 'GitHub', 'https://github.com/PigCI' %>
          </li>
          <li>
            <%= link_to 'Twitter', 'https://twitter.com/pig_ci' %>
          </li>
        </ul>
      </div>

      <div class="col-md-3">
        <div class="h5">Legal</div>
        
        <ul class="list-unstyled">
          <li>
            <%= link_to 'Privacy Policy', privacy_policy_path %>
          </li>
          <li>
            <%= link_to 'Terms of Service', terms_of_service_path %>
          </li>
          <li>
            <%= link_to 'Cookie Policy', cookie_policy_path %>
          </li>
          <li>
            <%= link_to 'Subprocessors', subprocessors_path %>
          </li>
        </ul>
      </div>

    </div>

    <div class="mt-3 small">
      <p>PigCI was created by <%= link_to 'Mike Rogers', 'https://mikerogers.io/', target: '_blank', rel: 'noopener' %> &copy; PigCI <%= Time.zone.today.year %></p>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<h1 class="sr-only"><%= title %></h1>

<div class="container pb-2 pt-3">
  <% if current_user %>
    <%= render 'shared/header/navbar_user' %>
  <% else %>
    <%= render 'shared/header/navbar_guest' %>
  <% end %>
  </nav>
</div>