config/routes.rb
Rails.application.routes.draw do
  # Have a path just for checking uptime, a no frills things to just check we're alive
  get :uptime_check, path: 'uptime-check', to: proc { [200, {}, ["Hello Robot - We're still up"]] }

  constraints subdomain: 'api' do
    namespace :api do
      namespace :v1 do
        resources :reports, only: [:create], defaults: { formats: :json }
      end
    end
    get '/', to: redirect("https://#{ENV['URL']}/api")
  end

  constraints subdomain: 'webhooks' do
    namespace :webhooks do
      resources :github, only: [:create], defaults: { formats: :json }
    end
    get '/', to: redirect("https://#{ENV['URL']}")
  end

  constraints subdomain: ['', 'www'] do
    devise_for :users,
               path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 sign_up: 'join-us'
               }, controllers: {
                 sessions: 'users/sessions',
                 omniauth_callbacks: 'users/omniauth_callbacks'
               }

    namespace :setup do
      resource :github, only: [:show]
    end

    resource :billing, only: [:show]
    resource :settings, only: [:show]

    resources :projects do
      member do
        get :delete
        get :setup
      end
      resources :report_collections, only: [:show] do
        resources :reports, only: [:show]
      end
    end

    get 'api', to: 'landing#api'
    get 'contact-us', to: 'landing#contact_us'
    get 'roadmap', to: 'landing#roadmap'

    get 'privacy-policy', to: 'legals#privacy_policy'
    get 'terms-of-service', to: 'legals#terms_of_service'
    get 'cookie-policy', to: 'legals#cookie_policy'
    get 'subprocessors', to: 'legals#subprocessors'
    get 'github-integration-deprecation-notice', to: 'legals#github_integration_deprecation_notice'

    get '', to: 'landing#index'
  end

  mount MountainView::Engine => '/styleguide'

  root to: redirect("https://#{ENV['URL']}")
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: %i[finders slugged history]

  belongs_to :install, counter_cache: true
  has_one :github_repository, dependent: :nullify
  has_many :github_check_suites, through: :github_repository
  has_many :reports
  has_many :report_collections, dependent: :destroy

  validates :name, presence: true
  validates :full_name, presence: true
  validates :api_key, presence: true, uniqueness: true
  validates :default_branch, presence: true
  validates :api_key, presence: true
  validates :memory_max, presence: true, numericality: { greater_than: 0, only_integer: true }
  validates :database_request_max, presence: true, numericality: { greater_than: 0, only_integer: true }
  validates :request_time_max, presence: true, numericality: { greater_than: 0, only_integer: true }

  before_validation :generate_api_key, unless: :api_key?

  def to_s
    name
  end

  def last_analysed_at!
    touch(:last_analysed_at)
  end

  def lastest_default_branch_report_collection
    @lastest_default_branch_report_collection ||= report_collections
                                                  .analysed
                                                  .where(branch: default_branch)
                                                  .newest
                                                  .includes(:reports)
                                                  .first
  end

  def lastest_default_branch_report_collection?
    lastest_default_branch_report_collection.present?
  end

  def lastest_report_collection
    @lastest_report_collection ||= lastest_default_branch_report_collection || report_collections.newest.includes(:reports).first
  end

  def lastest_report_collection?
    lastest_report_collection.present?
  end

  def pr_limits_changed?
    saved_changes.keys.any? do |key|
      key.in?(%w[memory_max database_request_max request_time_max])
    end
  end

  def memory_max
    @memory_max ||= ((memory_max_in_bytes || 1) / BigDecimal(1_048_576)).to_i
  end

  def memory_max=(value)
    @memory_max = nil
    self.memory_max_in_bytes = value.to_i * BigDecimal(1_048_576)
  end

  private

  def generate_api_key
    self.api_key = loop do
      token = SecureRandom.urlsafe_base64(32)
      break token unless Project.unscoped.exists?(api_key: token)
    end
  end

  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < AuthenticatedController
  before_action :set_project, only: %i[show edit setup update delete destroy]

  # GET /projects
  def index
    @projects = current_user.projects
    @github_repositories = current_user.github_repositories.where(project: nil).order(full_name: :asc)
  end

  # GET /projects/1
  def show
    set_meta_tags title: t('.title', project: @project, scope: ['meta_tags'])

    respond_to do |format|
      format.html do
        @report_collections = @project.report_collections.includes(:reports).newest.page(page_param)
      end
      format.json do
        @report_collections = @project.report_collections.newest.analysed.includes(:reports).page(page_param)
      end
    end
  end

  def setup
    set_meta_tags title: t('.title', project: @project, scope: ['meta_tags'])
  end

  # GET /projects/new
  def new
    @project = Project.new(install: current_user.installs.first)
  end

  # GET /projects/1/edit
  def edit
    set_meta_tags title: t('.title', project: @project, scope: ['meta_tags'])
  end

  # POST /projects
  def create
    @github_repository = current_user.github_repositories.find(params[:github_repository_id])

    @project = Project.new
    @project.attributes = {
      install: @github_repository.install,
      name: @github_repository.name,
      full_name: @github_repository.full_name,
      private: @github_repository.private,
      default_branch: @github_repository.default_branch
    }
    @github_repository.project = @project

    respond_to do |format|
      if @project.save && @github_repository.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
      else
        redirect_to new_project_path, alert: 'Unable to setup project'
      end
    end
  end

  # PATCH/PUT /projects/1
  def update
    respond_to do |format|
      if @project.update(project_params)
        Project::ReanalyseRecentReportCollectionsJob.perform_later(@project) if @project.pr_limits_changed?

        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def delete
    set_meta_tags title: t('.title', project: @project, scope: ['meta_tags'])
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = current_user.projects.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(
      :default_branch,
      :memory_max,
      :database_request_max,
      :request_time_max
    )
  end

  helper_method :page_param
  def page_param
    @page_param ||= params[:page] || 1
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <h2>Comparison Settings</h2>
    <%= f.input :default_branch %>
  </div>

  <div class="form-inputs mt-4">
    <h2>CI Settings</h2>

    <%= f.input :api_key, readonly: true, input_html: { name: nil } %>
  </div>

  <div class="form-inputs mt-4">
    <h2>PR Settings</h2>
    <p>PigCI can pass/fail PRs based on metrics. You will need to tweak these based on your needs.</p>

    <%= f.input :memory_max, wrapper: :input_group, append: 'mb' %>
    <%= f.input :database_request_max %>
    <%= f.input :request_time_max, wrapper: :input_group, append: 'ms'  %>
  </div>

  <div class="form-actions mt-3">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/_project.html+list.erb
<tr>
  <td scope="row"><%= link_to project.full_name, project_path(project) %></td>
  <td><%= project.created_at %></td>
  <td><%= project.updated_at %></td>
</tr>
      

app/views/projects/_project.html.erb
<div class="col-12 col-md-6 col-lg-4 d-flex align-items-stretch" data-controller="projects" data-projects-id="<%= project.id %>">
  <div class="card w-100 mb-4" data-target="projects.body">
    <div class="card-header">
      <%= link_to project.full_name, project_path(project), class: 'h5 mb-0' %>

      <div class="badge badge-pill badge-sm <%= project.conclusion_badge_status %> mt-1 float-right border border-white">&nbsp;</div>
    </div>
    <% if project.lastest_report_collection? %>
      <div class="card-body pb-0">
        <div class="row">
          <% project.lastest_report_collection.reports.max_value_for_collection_by_profiler.collect(&:decorate).each do |report| %>
            <div class="col-6 mb-2 text-center">
              <div class="small text-muted"><%= report.profiler %></div>
              <div class="font-weight-bold"><%= report.max_with_unit %></div>
            </div>
          <% end %>

          <div class="col-6 mb-2 text-center">
            <div class="small text-muted"><%= Report.human_attribute_name(:total_requests) %></div>
            <div class="font-weight-bold"><%= project.lastest_report_collection.reports.max_value_for_collection_by_profiler.first.decorate.total_requests %></div>
          </div>
        </div>
      </div>

      <%= link_to url_for(project), class: 'card-img-top charts d-block w-100', style: 'overflow: hidden; max-height: 150px;', id: "partial-project-chart-#{project.id}", 'data-turbolinks-permanent': true do %>
        <%= area_chart url_for([project, { format: :json }]), legend: false, discrete: false, height: 100,
          library: {
          responsive: true,
          tooltips: {
            enabled: false,
          },
          scales: {
            yAxes: [{
              stacked: false,
              ticks: { display: false, autoSkip: false, beginAtZero: false },
              gridLines: { display: false, drawBorder: false },
            }],
            xAxes: [{
              stacked: true,
              ticks: { display: false, autoSkip: false, beginAtZero: true },
              gridLines: { display: false, drawBorder: false },
              type: 'time',
              distribution: 'series'
            }],
          },
          layout: {
            padding: { top: 0, right: 0, bottom: -10, left: -10 },
          }
        } %>
      <% end %>
      <div class="card-footer text-center">
        <%= link_to 'View', project_path(project), class: 'card-link' %>
      </div>
    <% else %>
      <div class="card-body text-center">
        <p class="card-text">No data yet 🐷</p>
        <p class="card-text">Once we start receiving data, you'll see statistics here.</p>
      </div>
      <div class="card-footer text-center">
        <%= link_to 'Setup', project_path(project), class: 'card-link' %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/delete.html.erb
<div class="border-dashed p-4">
  <section class="text-center">
    <h2>Delete <%= @project %></h2>
    <p>Are you certain you want to delete <%= @project %>? <br />This action is irreversible and will delete all data we have associated to this project.</p>
    <%= link_to 'Yes, delete this project', project_path(@project), method: :delete, class: 'btn btn-danger' %>
  </section>
</div>

app/views/projects/edit.html.erb
<%= render 'form' %>

<section class="text-center text-muted small pt-3">
  <p>Do you want to <%= link_to 'delete your project', delete_project_path(@project) %>?</p>
</section>

app/views/projects/index.html.erb
<div class="">
  <div class="row">
    <%= render @projects.decorate %>
    <%= render 'projects/index/project_new' %>
    <%= render @github_repositories.decorate %>
  </div>
</div>

app/views/projects/new.html.erb
<% if current_user.installs.empty? %>
  <div class="border-dashed p-4 text-center">
    <h2>Not seeing your Repository?</h2>
    <p>You need to install our GitHub App onto your GitHub Account.</p>
    <%= link_to 'Install GitHub App', Rails.application.credentials.dig(Rails.env.to_sym, :github, :install_url), class: 'btn btn-infer-by-http-verb' %>
  </div>
<% else %>
  <div class="border-dashed p-4 text-center">
    <h2>Not seeing a repository?</h2>
    <p>You may need to adjust our Repository access on GitHub before you can start using it with PigCI.</p>
    <%= link_to 'Update GitHub App', Rails.application.credentials.dig(Rails.env.to_sym, :github, :install_url), class: 'btn btn-infer-by-http-verb' %>
  </div>
<% end %>

<% if current_user.github_repositories.any? %>
  <div class="table-responsive mt-3">
    <table class="table table-sort table-striped" data-controller="table-sort">
      <thead>
        <tr>
          <th scope="col">Repository</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% current_user.github_repositories.where(project: nil).decorate.each do |github_repository| %>
          <%= render partial: github_repository.to_partial_path, variants: [:list], locals: { github_repository: github_repository } %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/projects/setup.html.erb
<div class="border-dashed p-4">
  <section class="text-center mb-4">
    <h2>Setup PigCI</h2>
  </section>

  <%= render 'projects/setup/setup_instructions' %>

  <section>
    <p>Once you've ran your test suite, you'll see the metrics start appearing on your project page &amp; on GitHub.</p>
  </section>
</div>

app/views/projects/show.html.erb
<ul class="list-unstyled list-inline border rounded d-flex justify-content-between d-flex align-items-stretch flex-wrap">
  <li class="list-inline-item py-2 px-3">
    <strong><%= Project.human_attribute_name(:default_branch) %>:</strong> <%= @project.default_branch %>
  </li>
  <li class="list-inline-item py-2 px-3">
    <strong><%= Project.human_attribute_name(:api_key) %>:</strong>
    <%= link_to setup_project_path(@project) do %>
      <code><%= @project.api_key %></code>
    <% end %>
  </li>
  <li class="list-inline-item py-2 px-3">
    <%= link_to 'Settings', edit_project_path(@project) %>
  </li>
</ul>

<% if @project.report_collections.any? %>
  <%= render 'projects/show/default_branch_overview' if @project.lastest_report_collection? %>
  
  <h3 class="mt-3 h5" id="report-collections">Recent Results</h3>
  <%= render 'projects/show/recent_results' %>
<% else %>
  <%= render 'projects/show/first_time_setup' %>
<% end %>