config/routes.rb
Rails.application.routes.draw do
  # Have a path just for checking uptime, a no frills things to just check we're alive
  get :uptime_check, path: 'uptime-check', to: proc { [200, {}, ["Hello Robot - We're still up"]] }

  constraints subdomain: 'api' do
    namespace :api do
      namespace :v1 do
        resources :reports, only: [:create], defaults: { formats: :json }
      end
    end
    get '/', to: redirect("https://#{ENV['URL']}/api")
  end

  constraints subdomain: 'webhooks' do
    namespace :webhooks do
      resources :github, only: [:create], defaults: { formats: :json }
    end
    get '/', to: redirect("https://#{ENV['URL']}")
  end

  constraints subdomain: ['', 'www'] do
    devise_for :users,
               path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 sign_up: 'join-us'
               }, controllers: {
                 sessions: 'users/sessions',
                 omniauth_callbacks: 'users/omniauth_callbacks'
               }

    namespace :setup do
      resource :github, only: [:show]
    end

    resource :billing, only: [:show]
    resource :settings, only: [:show]

    resources :projects do
      member do
        get :delete
        get :setup
      end
      resources :report_collections, only: [:show] do
        resources :reports, only: [:show]
      end
    end

    get 'api', to: 'landing#api'
    get 'contact-us', to: 'landing#contact_us'
    get 'roadmap', to: 'landing#roadmap'

    get 'privacy-policy', to: 'legals#privacy_policy'
    get 'terms-of-service', to: 'legals#terms_of_service'
    get 'cookie-policy', to: 'legals#cookie_policy'
    get 'subprocessors', to: 'legals#subprocessors'
    get 'github-integration-deprecation-notice', to: 'legals#github_integration_deprecation_notice'

    get '', to: 'landing#index'
  end

  mount MountainView::Engine => '/styleguide'

  root to: redirect("https://#{ENV['URL']}")
end

app/models/report.rb
class Report < ApplicationRecord
  extend FriendlyId
  friendly_id :profiler, use: %i[finders slugged history scoped], scope: :report_collection_id

  belongs_to :report_collection
  belongs_to :project

  has_one_attached :raw_data

  enum profiler: {
    memory: 'memory',
    database_request: 'database_request',
    request_time: 'request_time'
  }
  enum conclusion: GithubCheckSuite.conclusions, _prefix: :conclusion

  validates :profiler, presence: true
  validates :raw_data, presence: true
  validates :branch, presence: true
  # validates :max, presence: true
  # validates :max_difference_from_default_branch, presence: true
  # validates :min, presence: true
  # validates :min_difference_from_default_branch, presence: true
  # validates :total_requests, presence: true

  scope :analysed, -> { where.not(analysed_at: nil) }
  scope :with_profiler, ->(profiler) { where(profiler: profiler) }
  scope :by_profiler_name, -> { order(profiler: :asc) }
  scope :created_before, ->(time) { analysed.where(created_at: [Time.at(0)..time]).newest }
  scope :max_value_for_collection_by_profiler, -> { sort_by(&:sort_by_max).uniq(&:profiler).sort_by(&:profiler) }

  before_validation do
    self.project = report_collection.project
    self.branch = report_collection.branch
  end

  def to_s
    Report.human_enum_name(:profiler, profiler)
  end

  def sort_by_max
    -max
  end

  def data=(value)
    @data = value
    raw_data.attach(io: StringIO.new(value.to_json), filename: "#{profiler}.json", content_type: 'application/json')
  end

  def data
    @data ||= JSON.parse(raw_data.blob.download, symbolize_names: true).sort_by do |row|
      BigDecimal(row[:max]) * -1
    end.collect do |row|
      row[:difference] = BigDecimal(row[:max]) - BigDecimal(row[:min])
      row
    end
  end

  def analyse!
    self.attributes = {
      max: data.collect { |row| BigDecimal(row[:max]) }.max,
      min: data.collect { |row| BigDecimal(row[:min]) }.min,
      total_requests: data.collect { |row| row[:number_of_requests].to_i }.inject(0, :+)
    }

    self.max_difference_from_default_branch = calc_max_difference_from_default_branch
    self.min_difference_from_default_branch = calc_min_difference_from_default_branch

    self.conclusion = calc_conclusion

    self.analysed_at = current_time_from_proper_timezone
    save!
  end

  def calc_conclusion
    return 'neutral' unless profiler.in?(%w[memory database_request request_time])

    if (max / unit_scaling_modifier) >= project.send("#{profiler}_max")
      'failure'
    elsif max_difference_from_default_branch >= BigDecimal(0)
      'neutral'
    else
      'success'
    end
  end

  def calc_max_difference_from_default_branch
    previous_max = previous_report_from_default_branch&.max || 0
    difference_from_default = BigDecimal(max) / BigDecimal(previous_max || max)

    return BigDecimal(0) if difference_from_default.zero? || !difference_from_default.finite?

    (difference_from_default * BigDecimal(100)) - BigDecimal(100)
  end

  def calc_min_difference_from_default_branch
    previous_min = previous_report_from_default_branch&.min || 0
    difference_from_default = BigDecimal(min) / BigDecimal(previous_min || min)

    return BigDecimal(0) if difference_from_default.zero? || !difference_from_default.finite?

    (difference_from_default * BigDecimal(100)) - BigDecimal(100)
  end

  def previous_report_from_default_branch
    @previous_report_from_default_branch = project.reports
                                                  .analysed
                                                  .with_profiler(profiler)
                                                  .created_before(created_at)
                                                  .where(branch: project.default_branch)
                                                  .where.not(id: id)
                                                  .newest
                                                  .first
  end

  def unit
    @unit ||= if profiler == 'memory'
                'mb'
              elsif profiler == 'request_time'
                'ms'
              else
                ''
              end
  end

  def unit_scaling_modifier
    @unit_scaling_modifier ||= profiler == 'memory' ? BigDecimal(1_048_576) : BigDecimal(1)
  end

  private

  def slug_candidates
    [profiler, SecureRandom.uuid].join('-')
  end

  def should_generate_new_friendly_id?
    slug.blank?
  end
end

app/controllers/api/v1/reports_controller.rb
class Api::V1::ReportsController < ActionController::API
  before_action :set_report, only: [:create]

  def create
    @report_form.attributes = report_form_params

    if @report_form.valid?(:schema_validation) && @report_form.save
      head :ok
    else
      render json: @report_form.errors, status: :unprocessable_entity
    end
  end

  private

  def render_api_key_unauthorized!
    render json: {
      error: 'API Key is invalid'
    }, status: :unauthorized
  end

  def set_report
    @project = Project.find_by!(api_key: request.headers.env['HTTP_X_APIKEY'])
    @report_form = ReportCollection::CreateForm.new(project: @project)

  rescue ActiveRecord::RecordNotFound
    render_api_key_unauthorized!
  end

  def report_form_params
    @report_form_params ||= params.permit(
      :library,
      :library_version,
      :commit_sha1,
      :head_branch,
      :reporter_name,
      reports: [
        :profiler, data: %i[
          key max min mean total number_of_requests max_change_percentage
        ]
      ]
    )
  end
end

app/controllers/reports_controller.rb
class ReportsController < AuthenticatedController
  before_action :set_report_and_parents, only: [:show]

  # GET /reports/1
  # GET /reports/1.json
  def show
    @render_unhappy_pig_logo = @report.conclusion_failure?

    set_meta_tags title: t('.title', report: @report, report_collection: @report_collection, project: @project, scope: ['meta_tags'])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report_and_parents
    @project = current_user.projects.find(params[:project_id])
    @report_collection = @project.report_collections.find(params[:report_collection_id]).decorate
    @report = @report_collection.reports.find(params[:id]).decorate
  end
end

app/views/reports/_report.html.erb
<div class="col-12 col-md-6 col-lg-4 d-flex align-items-stretch">
  <div class="card w-100 mb-4">
    <div class="card-header">
      <%= link_to report.profiler, project_report_collection_report_path(report.project, report.report_collection, report), class: 'h5 mb-0' %>
      <div class="badge badge-pill badge-sm <%= report.change_percentage_badge_status %> mt-1 float-right border border-white">&nbsp;</div>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-6 text-center">
          <%= render_stat_for(report, :max_with_unit) %>
        </div>
        <div class="col-6 text-center">
          <%= render_stat_for(report, :min_with_unit) %>
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-6 text-center">
          <%= render_stat_for(report, :total_requests) %>
        </div>
        <div class="col-6 text-center">
          <%= render_stat_for(report, :change_percentage_with_unit) %>
        </div>
      </div>
    </div>
    <div class="card-footer text-center">
      <%= link_to 'View', project_report_collection_report_path(report.project, report.report_collection, report), class: 'card-link' %>
    </div>
  </div>
</div>

app/views/reports/show.html.erb
<div class="row mb-3">
  <div class="col-4 text-center">
    <%= render_stat_for(@report_collection, :last_analysed_at) %>
  </div>
  <div class="col-4 text-center">
    <%= render_stat_for(@report, :change_percentage_with_unit) %>
  </div>
  <div class="col-4 text-center">
    <%= render_stat_for(@report, :conclusion) %>
  </div>
</div>

<div class="charts mb-5 w-100" id="report-chart-<%= @report.id %>" data-turbolinks-permanent="true" style="overflow: hidden; max-height: 150px;">
  <%= column_chart(project_report_collection_report_path(@report.project, @report.report_collection, @report, { format: :json }),
    legend: false, discrete: false, height: 200, suffix: @report.unit,
    library: {
      responsive: true,
      tooltips: {
        enabled: true,
        mode: 'index',
        position: 'nearest'
      },
      scales: {
        yAxes: [{
          stacked: false,
          ticks: { display: true, autoSkip: false, beginAtZero: true },
          gridLines: { display: true },
        }],
        xAxes: [{
          stacked: true,
          ticks: { display: false, autoSkip: false, beginAtZero: true },
          gridLines: { display: true },
        }],
      },
      layout: {
        padding: { top: 0, right: 0, bottom: 0, left: 0 },
      }
    }
  )%>
</div>

<div class="table-responsive">
  <table class="table table-sort table-striped" data-controller="table-sort">
    <thead>
      <tr>
        <th scope="col"><%= Report.human_attribute_name(:key) %></th>
        <th scope="col"><%= Report.human_attribute_name(:max) %></th>
        <th scope="col"><%= Report.human_attribute_name(:min) %></th>
        <th scope="col"><%= Report.human_attribute_name(:number_of_requests) %></th>
      </tr>
    </thead>
    <tbody>
      <% ReportRowDecorator.decorate_collection(@report.data, context: { profiler: @report.object.profiler }).each do |row| %>
        <tr>
          <th scope="row"><%= row.key %></th>
          <td><%= row.max %><%= @report.unit %></td>
          <td><%= row.min %><%= @report.unit %></td>
          <td><%= row.number_of_requests %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>